language: ruby
rvm:
  - 2.2.2
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  - REDSHIFT_URL="redshift://postgres@localhost/travis_ci_test"
before_install: gem install bundler -v 1.10.5
