language: ruby
rvm:
  - 2.2.2
addons:
  postgresql: "9.4"
cache: bundler
before_script:
  - createdb travis_ci_test
env:
  - REDSHIFT_URL="redshift://postgres@localhost:5432/travis_ci_test"
script: bundle exec rake spec
